routes/web.php
Route::get('createanunit', ['uses' => 'Lini1AnalisisCtrl@create', 'as' => 'createanunit']);
Route::get('lini1analisis', ['uses' => 'Lini1AnalisisCtrl@index', 'as' => 'lini1analisis']);
Route::resource('lini1analisis', 'Lini1AnalisisCtrl');
Route::get('lini1pengendalian/{id}/tambah', ['as' => 'lini1pengendalian.tambah', 'uses' => 'Lini1PengendalianCtrl@tambah']);
Route::get('lini1pengendalian', ['uses' => 'Lini1PengendalianCtrl@index', 'as' => 'lini1pengendalian']);
Route::resource('lini1pengendalian', 'Lini1PengendalianCtrl');
Route::get('lini1residual', ['uses' => 'Lini1ResidualCtrl@index', 'as' => 'lini1residual']);
Route::resource('lini1residual', 'Lini1ResidualCtrl');
// Evaluasi Risiko
Route::get('penyebabunit', 'Lini1EvaluasiCtrl@getPenyebabUnit');
Route::get('penyebablistunit', 'Lini1EvaluasiCtrl@getPenyebabListUnit');
Route::get('penyebablistunit/{id}', 'Lini1EvaluasiCtrl@getFilterPenyebabListUnit');
Route::get('cetakevunit', 'Lini1EvaluasiCtrl@cetakRisiko');
Route::get('cetakrcaunit', 'Lini1EvaluasiCtrl@cetakRCA');
Route::get('createevunit', ['uses' => 'Lini1EvaluasiCtrl@create', 'as' => 'createevunit']);
Route::get('lini1evaluasi', ['uses' => 'Lini1EvaluasiCtrl@index', 'as' => 'lini1evaluasi']);
Route::resource('lini1evaluasi', 'Lini1EvaluasiCtrl');
// Respons Risiko (Rencana)
Route::get('rtpunit', 'Lini1ResponsCtrl@getRTPUnit');
Route::get('rtplistunit', 'Lini1ResponsCtrl@getRTPListUnit');
Route::get('rtplistcurunit', 'Lini1ResponsCtrl@getRTPListCurUnit');
Route::get('cetakresunit', 'Lini1ResponsCtrl@cetak');
Route::get('createrespunit', ['uses' => 'Lini1ResponsCtrl@create', 'as' => 'createrespunit']);
Route::get('lini1respons', ['uses' => 'Lini1ResponsCtrl@index', 'as' => 'lini1respons']);
Route::resource('lini1respons', 'Lini1ResponsCtrl');
Route::get('lini1treated', ['uses' => 'Lini1TreatedCtrl@index', 'as' => 'lini1treated']);
Route::resource('lini1treated', 'Lini1TreatedCtrl');
// Respons Risiko (Realisasi)
Route::get('monitorunit', 'Lini1ResponsCtrl@getMonitorUnit');
Route::get('reslambatunit', 'Lini1ResponsCtrl@getResLambatUnit');
Route::get('cetakrealunit', 'Lini1RealisasiCtrl@cetak');
Route::get('createrealunit', ['uses' => 'Lini1RealisasiCtrl@create', 'as' => 'createrealunit']);
Route::get('lini1realisasi', ['uses' => 'Lini1RealisasiCtrl@index', 'as' => 'lini1realisasi']);
Route::resource('lini1realisasi', 'Lini1RealisasiCtrl');
// Monitoring Risiko
Route::get('insidenunit', 'Lini1MonitoringCtrl@getInsidenUnit');
Route::get('inskejadianunit', 'Lini1MonitoringCtrl@getInsKejadianUnit');
Route::get('insrisikounit', 'Lini1MonitoringCtrl@getInsRisikoUnit');
Route::get('insrisikounit/{id}', 'Lini1MonitoringCtrl@getFilterInsRisikoUnit');
Route::get('inssebabunit', 'Lini1MonitoringCtrl@getInsSebabUnit');
Route::get('inssebabunit/{id}', 'Lini1MonitoringCtrl@getFilterInsSebabUnit');
Route::get('cetakmonunit', 'Lini1MonitoringCtrl@cetak');
Route::get('createmonitorunit', ['uses' => 'Lini1MonitoringCtrl@create', 'as' => 'createmonitorunit']);
Route::get('lini1monitoring', ['uses' => 'Lini1MonitoringCtrl@index', 'as' => 'lini1monitoring']);
Route::resource('lini1monitoring', 'Lini1MonitoringCtrl');
// Pelaporan Risiko
Route::get('lini1laporan', ['uses' => 'Lini1LaporanCtrl@index', 'as' => 'lini1laporan']);
Route::resource('lini1laporan', 'Lini1LaporanCtrl');
}); //namespace
}); //roles

}); //middleware
//
// Lini 2
//
Route::get('/lini2tetapkonteks/pilihKonteks/{id}', 'lini2\Lini2TetapKonteksCtrl@pilihKonteks');
Route::get('/lini2identifikasi/pilihKonteksUnit/{id}', 'lini2\Lini2IdentifikasiCtrl@pilihKonteksUnit');
Route::get('/lini2analisis/pilihRisikoUnit/{id}', 'lini2\Lini2AnalisisCtrl@pilihRisikoUnit');
Route::get('/lini2analisis/pilihSkor/{id}/{id2}', 'lini2\Lini2AnalisisCtrl@pilihSkor');
Route::get('/lini2evaluasi/pilihRisikoUnit2/{id}', 'lini2\Lini2EvaluasiCtrl@pilihRisikoUnit2');
Route::get('/lini2respons/pilihSebab/{id}', 'lini2\Lini2ResponsCtrl@pilihSebab');
Route::get('/lini2realisasi/pilihRTP/{id}', 'lini2\Lini2RealisasiCtrl@pilihRTP');
Route::get('/lini2realisasi/pilihPeriodeRTP/{id}', 'lini2\Lini2RealisasiCtrl@pilihPeriodeRTP');
Route::get('/lini2monitoring/pilihSebab2/{id}', 'lini2\Lini2MonitoringCtrl@pilihSebab2');

Route::group(['middleware' => ['web', 'auth', 'roles']],function() {
Route::group(['roles' => '1' or '2' or '3' or '8'],function() { 
Route::namespace('lini2')->group(function () {
// Parameter
Route::get('lini2data', ['uses' => 'Lini2DataCtrl@index', 'as' => 'lini2data']);
Route::resource('lini2data', 'Lini2DataCtrl');
Route::get('createparamkonteks', ['uses' => 'Lini2ParamKonteksCtrl@create', 'as' => 'createparamkonteks']);
Route::get('lini2paramkonteks', ['uses' => 'Lini2ParamKonteksCtrl@index', 'as' => 'lini2paramkonteks']);
Route::resource('lini2paramkonteks', 'Lini2ParamKonteksCtrl');
Route::get('createparamrisiko', ['uses' => 'Lini2ParamRisikoCtrl@create', 'as' => 'createparamrisiko']);
Route::get('lini2paramrisiko', ['uses' => 'Lini2ParamRisikoCtrl@index', 'as' => 'lini2paramrisiko']);
Route::resource('lini2paramrisiko', 'Lini2ParamRisikoCtrl');
Route::get('createparamrole', ['uses' => 'Lini2ParamRoleCtrl@create', 'as' => 'createparamrole']);
Route::get('lini2paramrole', ['uses' => 'Lini2ParamRoleCtrl@index', 'as' => 'lini2paramrole']);
Route::resource('lini2paramrole', 'Lini2ParamRoleCtrl');
Route::get('createparamuser', ['uses' => 'Lini2ParamUserCtrl@create', 'as' => 'createparamuser']);
Route::get('ubahparamuser', ['uses' => 'Lini2ParamUserCtrl@ubah', 'as' => 'ubahparamuser']);
Route::post('simpanparamuser', ['uses' => 'Lini2ParamUserCtrl@simpan', 'as' => 'simpanparamuser']);
Route::get('lini2paramuser', ['uses' => 'Lini2ParamUserCtrl@index', 'as' => 'lini2paramuser']);
Route::resource('lini2paramuser', 'Lini2ParamUserCtrl');
// Penetapan Konteks
Route::get('lini2tetapkonteks/{id}/delete', ['as' => 'lini2tetapkonteks.delete', 'uses' => 'Lini2TetapKonteksCtrl@delete']);
Route::get('lini2tetapkonteks/{id}/batal', ['as' => 'lini2tetapkonteks.batal', 'uses' => 'Lini2TetapKonteksCtrl@batal']);
Route::get('createtetapkonteks', ['uses' => 'Lini2TetapKonteksCtrl@create', 'as' => 'createtetapkonteks']);
Route::get('lini2tetapkonteks', ['uses' => 'Lini2TetapKonteksCtrl@index', 'as' => 'lini2tetapkonteks']);
Route::resource('lini2tetapkonteks', 'Lini2TetapKonteksCtrl');
// Identifikasi Risiko
Route::get('peta', ['uses' => 'Lini2IdentifikasiCtrl@getDashPeta', 'as' => 'peta']);
Route::get('heatmap', ['uses' => 'Lini2IdentifikasiCtrl@getHeatmap', 'as' => 'heatmap']);
Route::get('registerunit/{id}', 'Lini2IdentifikasiCtrl@getRegisterUnit');
Route::get('dashboardregister', 'Lini2IdentifikasiCtrl@getDashRegister');
Route::get('dashboardregister/{id}', 'Lini2IdentifikasiCtrl@getFilterRegister');
Route::get('createidentifikasi', ['uses' => 'Lini2IdentifikasiCtrl@create', 'as' => 'createidentifikasi']);
Route::get('lini2identifikasi', ['uses' => 'Lini2IdentifikasiCtrl@index', 'as' => 'lini2identifikasi']);
Route::resource('lini2identifikasi', 'Lini2IdentifikasiCtrl');
// Analisis Risiko
Route::get('skoranalisis', 'Lini2AnalisisCtrl@getSkorAnalisis');
Route::get('createanalisis', ['uses' => 'Lini2AnalisisCtrl@create', 'as' => 'createanalisis']);
Route::get('lini2analisis', ['uses' => 'Lini2AnalisisCtrl@index', 'as' => 'lini2analisis']);
Route::resource('lini2analisis', 'Lini2AnalisisCtrl');
// Evaluasi Risiko
Route::get('penyebab', 'Lini2EvaluasiCtrl@getPenyebab');
Route::get('penyebablist', 'Lini2EvaluasiCtrl@getPenyebabList');
Route::get('penyebablist/{id}', 'Lini2EvaluasiCtrl@getFilterPenyebabList');
Route::get('createevaluasi', ['uses' => 'Lini2EvaluasiCtrl@create', 'as' => 'createevaluasi']);
Route::get('lini2evaluasi', ['uses' => 'Lini2EvaluasiCtrl@index', 'as' => 'lini2evaluasi']);
Route::resource('lini2evaluasi', 'Lini2EvaluasiCtrl');
// Respons Risiko (Rencana)
Route::get('rtp', 'Lini2ResponsCtrl@getRTP');
Route::get('rtplist', 'Lini2ResponsCtrl@getRTPList');
Route::get('rtplistcurrent', 'Lini2ResponsCtrl@getRTPListCurrent');
Route::get('createrespons', ['uses' => 'Lini2ResponsCtrl@create', 'as' => 'createrespons']);
Route::get('lini2respons', ['uses' => 'Lini2ResponsCtrl@index', 'as' => 'lini2respons']);
Route::resource('lini2respons', 'Lini2ResponsCtrl');
Route::get('lini2treated', ['uses' => 'Lini2TreatedCtrl@index', 'as' => 'lini2treated']);
Route::resource('lini2treated', 'Lini2TreatedCtrl');
// Respons Risiko (Realisasi)
Route::get('monitor', 'Lini2ResponsCtrl@getMonitor');
Route::get('responslambat', 'Lini2ResponsCtrl@getResponsLambat');
Route::get('createrealisasi', ['uses' => 'Lini2RealisasiCtrl@create', 'as' => 'createrealisasi']);
Route::get('lini2realisasi', ['uses' => 'Lini2RealisasiCtrl@index', 'as' => 'lini2realisasi']);
Route::resource('lini2realisasi', 'Lini2RealisasiCtrl');
// Monitoring Risiko
Route::get('insiden', 'Lini2MonitoringCtrl@getInsiden');
Route::get('insidenkejadian', 'Lini2MonitoringCtrl@getInsidenKejadian');
Route::get('insidenrisiko', 'Lini2MonitoringCtrl@getInsidenRisiko');
Route::get('insidenrisiko/{id}', 'Lini2MonitoringCtrl@getFilterInsidenRisiko');
Route::get('insidensebab', 'Lini2MonitoringCtrl@getInsidenSebab');
Route::get('insidensebab/{id}', 'Lini2MonitoringCtrl@getFilterInsidenSebab');
Route::get('createmonitoring', ['uses' => 'Lini2MonitoringCtrl@create', 'as' => 'createmonitoring']);
Route::get('lini2monitoring', ['uses' => 'Lini2MonitoringCtrl@index', 'as' => 'lini2monitoring']);
Route::resource('lini2monitoring', 'Lini2MonitoringCtrl');
}); //namespace
}); //roles
}); //middleware
//
// v2.0 akhir

Route::get('/', function() {
	return redirect('/login');
});

Route::get('/login', ['uses' => 'admin\AuthCtrl@getLogin','as' => 'login']); 
Route::post('/login', ['uses' => 'admin\AuthCtrl@postLogin']);
Route::get('/peran', ['uses' => 'admin\AuthCtrl@getPeran','as' => 'peran']); 
Route::post('/peran', ['uses' => 'admin\AuthCtrl@postPeran']);
Route::post('/logout', ['uses' => 'admin\AuthCtrl@getLogout','as' => 'logout']);

resources/views/lini2treated/edit.blade.php
@extends('layout.app')

@section('isi')
<div class="slim-pageheader">
  <ol class="breadcrumb slim-breadcrumb">
    <li class="breadcrumb-item"><a href="{{route('peta')}}"><i class="fa fa-home"></i> Home</a></li>
    <li class="breadcrumb-item active" aria-current="page">Respons Risiko</li>
  </ol>
  <h6 class="slim-pagetitle">Respons Risiko</h6>
</div><!-- slim-pageheader -->
<div class="card card-table">
  <div class="card-header">
    <h6>Nama Pemilik Risiko:</h6>
    <h6 style="color: black;">{{$s_nmjabdetail->nama}}</h6>
  </div>
  <div class="card-header">
    <h6>Nama Risiko:</h6>
    <h6 style="color: black;">{{$nama_bagan_risiko->risiko}}</h6>
  </div>
  <!-- /.box-header -->
  <div class="card card-table">
  <div class="card-header">
    <h6 class="slim-card-title">Residual Risk</h6>
  </div>
    <form class="form-horizontal mt-2">
    <div class="box-body">
      <div class="form-inline">
        <label for="kemungkinan_residual" class="col-sm-2 control-label">Kemungkinan Residual :</label>
        <div class="col-sm-2">
          <input class="form-control" value="{{$residual->skor_kemungkinan}}" name="kemungkinan_residual" id="kemungkinan_residual" readonly></input>
        </div>
        <label for="dampak_residual" class="col-sm-2 control-label">Dampak Residual :</label>
        <div class="col-sm-2">
          <input class="form-control" value="{{$residual->skor_dampak}}" name="dampak_residual" id="dampak_residual" readonly></input>
        </div>
        <label for="id_matriks_residual" class="col-sm-2 control-label">Level Risiko Residual :</label>
        <div class="col-sm-2">
          <input class="form-control" value="{{$residual->skor_risiko}}" name="id_matriks_residual" id="id_matriks_residual" readonly></input>
        </div>
      </div>
      <br/>
    </div>
      <!-- /.box-body -->
    </form>
  </div>


  <div class="pd-20">
    <center><h5 style="color: black;">Rencana Tindak Pengendalian</h5></center>
    <div class="table-wrapper">
    {{ csrf_field() }}

    <table id="tbl-identifikasi" class="table display responsive">
      <thead align="center">
        <tr>
          <th width="3%">No.</th>
          <th style="text-align: center;">Nama Penyebab</th>
          <th style="text-align: center;">Respons Risiko</th>
          <th style="text-align: center;">Kegiatan Pengendalian</th>
        </tr>
      </thead>
      <tbody>
      <?php $no=1; ?>
      @foreach($treated as $item)
        <tr class="item{{$item->id}}">
          <td>{{$no++}}</td>
          <td>{{$item->nama_akar_penyebab}}</td>
          <td>
            @if($item->respon_risiko == "K")
                    Mengurangi Kemungkinan 
            @elseif($item->respon_risiko == "D")
                    Mengurangi Dampak
            @else($item->respon_risiko == "B")
                    Mengurangi Kemungkinan dan Dampak
            @endif
          </td>
          <td>{{$item->kegiatan_pengendalian}}</td>
        </tr>
      @endforeach
      </tbody>
    </table>
  </div>
  </div>
</div>

<div class="card card-table">
  <div class="card-header">
    <h6 class="slim-card-title">Penilaian Treated Risk</h6>
  </div>

  @if ($errors->any())
      <div class="alert alert-danger">
          <ul>
              @foreach ($errors->all() as $error)
                  <li>{{ $error }}</li>
              @endforeach
          </ul>
      </div>
  @endif

  @if (Auth::user()->role_id == '1')
  <form class="form-horizontal mt-2" action="{{route('lini2treated.update', $analisis->id_analisis)}}" method="post">
    {{ csrf_field() }}
    {{ method_field('PUT') }}
    <input type="hidden" name="id_analisis" value="{{$analisis->id_analisis}}">

    <div class="box-body">

      <div class="form-inline">
        <label for="kemungkinan_treated" class="col-sm-2 control-label">Kemungkinan Treated :</label>
        <div class="col-sm-2">
          <select class="form-control" name="kemungkinan_treated" id="kemungkinan_treated">
            @foreach($kemungkinan_treated as $per)
            <option value="{{$per}}" {{old('kemungkinan_treated') == $per ? 'selected' : ''}}>{{$per}}</option>
            @endforeach
          </select>
        </div>
        <label for="dampak_treated" class="col-sm-2 control-label">Dampak Treated :</label>
        <div class="col-sm-2">
          <select class="form-control" name="dampak_treated" id="dampak_treated">
            @foreach($dampak_treated as $per)
            <option value="{{$per}}" {{old('dampak_treated') == $per ? 'selected' : ''}}>{{$per}}</option>
            @endforeach
          </select>
        </div>
        <label for="id_matriks_treated" class="col-sm-2 control-label">Level Risiko Treated :</label>
        <div class="col-sm-2">
          <select name="id_matriks_treated" class="form-control" id="id_matriks_treated">
          <option value="0" disabled="true" selected="true"></option>
          <option value="">-- Pilih Kemungkingan/Dampak Risiko Treated--</option>
          </select>
        </div>
      </div>

      <br/>

      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-12">
          <button type="submit" class="btn btn-primary"> Simpan</button>
          <a href="{{route('lini2respons.index')}}" type="submit" class="btn btn-danger"><i class="icon ion-android-cancel"></i> Batal</a>
        </div>
      </div>
      
    </div>
      <!-- /.box-body -->
  </form>
  @endif
  </div>

</div>
@stop


@push('js')
  <script>
  $(function(){
    'use strict';
    $('#tbl-identifikasi').DataTable({
      responsive: true,
      language: {
        searchPlaceholder: 'Search...',
        sSearch: '',
        lengthMenu: '_MENU_ items/page',
      }
    });

    // Select2
    $('.dataTables_length select').select2({ minimumResultsForSearch: Infinity });
  });

    $(document).ready(function() {
    $("#kemungkinan_treated").select2();
    $("#dampak_treated").select2();
    $("#id_matriks_treated").select2();

});

  </script>
@endpush

@push('js1')
  <script type="text/javascript">

  $(document).ready(function() {

        $('#kemungkinan_treated').select2().on('change', function() {
            var kemungkinanID = $(this).val();
            var dampakID = $('#dampak_treated').val();
            console.log(kemungkinanID);
            if(kemungkinanID) {
                $.ajax({
                    url: '/bewise20/lini2analisis/pilihSkor/'+kemungkinanID+'/'+dampakID,
                    type: 'get',
                    dataType: 'json',
                    success:function(data) {
                      console.log(data);
                        $('select[name="id_matriks_treated"]').empty();
                        $.each(data, function(key, value) {
                            $('select[name="id_matriks_treated"]').append('<option value="'+ value.id_matriks +'">'+ value.skor_risiko + '</option>');
                        });

                    }
                });
            } else {
                $('select[name="id_matriks_treated"]').empty();
            }
        });

        $('#dampak_treated').select2().on('change', function() {
            var dampakID = $(this).val();
            var kemungkinanID = $('#kemungkinan_treated').val();
            console.log(dampakID);
            if(dampakID) {
                $.ajax({
                    url: '/bewise20/lini2analisis/pilihSkor/'+kemungkinanID+'/'+dampakID,
                    type: 'get',
                    dataType: 'json',
                    success:function(data) {
                      console.log(data);
                        $('select[name="id_matriks_treated"]').empty();
                        $.each(data, function(key, value) {
                            $('select[name="id_matriks_treated"]').append('<option value="'+ value.id_matriks +'">'+ value.skor_risiko + '</option>');
                        });

                    }
                });
            } else {
                $('select[name="id_matriks_treated"]').empty();
            }
        });

        $('#id_matriks_treated').select2()

  });
  </script>
@endpush

resources/views/lini2treated/index.blade.php
@extends('layout.app')

@section('isi')
<div class="slim-pageheader">
  <ol class="breadcrumb slim-breadcrumb">
    <li class="breadcrumb-item"><a href="{{route('peta')}}"><i class="fa fa-home"></i> Home</a></li>
    <li class="breadcrumb-item active" aria-current="page">Respons Risiko</li>
  </ol>
  <h6 class="slim-pagetitle">Penilaian Treated Risk</h6>
</div><!-- slim-pageheader -->
<div class="card card-table">
  <div class="card-header">
    <h5 style="color: black;">Nama Pemilik Risiko:</h5>

  </div>
  <div class="card-header">
    <h5 style="color: black;">Nama Risiko:</h5>
    
  </div>
  <!-- /.box-header -->
  <div class="pd-20">
    <center><h3 style="color: black;">Rencana Tindak Pengendalian</h3></center>
    <div class="table-wrapper">
    {{ csrf_field() }}

    <table id="tbl-identifikasi" class="table display responsive">
      <thead align="center">
        <tr>
          <th width="3%">No.</th>
          <th style="text-align: center;">Nama Risiko</th>
          <th style="text-align: center;">Nilai Inherent Risk</th>
          <th style="text-align: center;">E.C. Ada</th>
          <th style="text-align: center;">Existing Control</th>
          <th style="text-align: center;">E.C. Memadai</th>
          <th style="text-align: center;">Nilai Residual Risk</th>
        </tr>
      </thead>
      <tbody>
      <?php $no=1; ?>
      @foreach($analisis as $item)
        <tr class="item{{$item->id}}">
          <td>{{$no++}}</td>
          <td>{{$item->nama_bagan_risiko}}</td>
          <td style="text-align: center;">{{$item->skor_risiko_inherent}}</td>
          <td style="text-align: center;">{{$item->existing_control}}</td>
          <td>{{$item->uraian_existing_control}}</td>
          <td style="text-align: center;">{{$item->existing_control_memadai}}</td>
          <td style="text-align: center;">{{$item->skor_risiko_residual}}</td>
        </tr>
      @endforeach
      </tbody>
    </table>
  </div>
  </div>
</div>
@endsection

@push('js')
  <script>
  $(function(){
    'use strict';
    $('#tbl-identifikasi').DataTable({
      responsive: true,
      language: {
        searchPlaceholder: 'Search...',
        sSearch: '',
        lengthMenu: '_MENU_ items/page',
      }
    });

    // Select2
    $('.dataTables_length select').select2({ minimumResultsForSearch: Infinity });
  });

  </script>
@endpush